// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about.tsx";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/api/uuid.ts";
import * as $7 from "./routes/github/[username].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/middlewareTestHandlder.ts";
import * as $10 from "./routes/search.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/about.tsx": $4,
    "./routes/api/joke.ts": $5,
    "./routes/api/uuid.ts": $6,
    "./routes/github/[username].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/middlewareTestHandlder.ts": $9,
    "./routes/search.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
